# Generated by Django 2.2 on 2019-04-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя документа')),
                ('image', models.FileField(blank=True, null=True, upload_to='document_file')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('short_desc', models.CharField(blank=True, max_length=60, null=True, verbose_name='краткое описание Документа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание Документа')),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная категория')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя мероприятия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images')),
                ('short_desc', models.CharField(blank=True, max_length=60, null=True, verbose_name='краткое описание мероприятия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание мероприятия')),
                ('timeofevent', models.CharField(blank=True, max_length=60, null=True, verbose_name='дата мероприятия')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='количество зрителей')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная категория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.EventCategory')),
            ],
        ),
    ]
