# Generated by Django 2.2 on 2019-04-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Anketa', max_length=64, verbose_name='титул')),
                ('full_name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('age', models.IntegerField(default=18, verbose_name='возраст')),
                ('phone_number', models.CharField(blank=True, max_length=64, verbose_name='телефон')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='город')),
                ('about', models.TextField(blank=True, max_length=64, verbose_name='описание')),
                ('sender', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
